version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    # environment:
    #   - DATABASE_URL=/pkg/db/sqlite/social-network.db

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  # db:
  #   image: "sqlite:latest"
  #   volumes:
  #     - ./data:/data


