CREATE TABLE IF NOT EXISTS GroupPosts (
    id INTEGER PRIMARY KEY,
    group_id INTEGER REFERENCES Groups(id),
    post_id INTEGER REFERENCES Posts(id),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);